name: steps_tracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^2.0.4
  auto_route: ^1.0.2
  injectable: ^1.2.2
  flash: ^1.5.1

  # firebase
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.4
  firebase_messaging: ^9.1.2

  pedometer: ^2.1.0
  font_awesome_flutter: ^9.0.0
  theme_mode_builder: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2
  auto_route_generator: ^1.0.2
  injectable_generator: ^1.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
