name: steps_tracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^2.1.1
  auto_route: ^2.0.2
  injectable: ^1.3.0
  flash: ^1.5.2

  # firebase
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^2.0.0
  firebase_messaging: ^9.1.3
  firebase_storage: ^8.0.5

  pedometer: ^3.0.0
  font_awesome_flutter: ^9.0.0
  theme_mode_builder: ^1.0.1
  image_picker: ^0.7.4
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.2
  auto_route_generator: ^2.0.1
  injectable_generator: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
